language: python
dist: xenial
sudo: true

python: 3.7

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install -r requirements-dev.txt

script:
  - pycodestyle .
  - flake8
  - coverage run manage.py test -v 2